version: '3'

services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_DBNAME=postgis
    ports:
      - "5432:5432"